apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "node-group-scaler.fullname" . }}
  labels:
    {{- include "node-group-scaler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "node-group-scaler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "node-group-scaler.selectorLabels" . | nindent 8 }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "node-group-scaler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AWS_REGION
              value: {{ .Values.aws.region }}
            - name: LOG_LEVEL
              value: {{ .Values.operator.logLevel }}
            - name: COOLDOWN_PERIOD
              value: {{ .Values.operator.cooldownPeriod | quote }}
          ports:
            - name: metrics
              containerPort: {{ .Values.operator.metricsPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 