apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-group-scaler.fullname" . }}
  labels: {{- include "node-group-scaler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector: {{- include "node-group-scaler.selectorLabels" . | nindent 4 }}
